fix

diff --git a/bash_dru b/bash_dru
--- a/bash_dru
+++ b/bash_dru
@@ -35,3 +35,19 @@ alias ska='echo "Killing core audio"; sudo killall coreaudiod;'
 alias bump="git commit -a -m \"Bump build no\""
 alias clear-derived-data='rm -rf ~/Library/Developer/Xcode/DerivedData'
 alias grepr='grep -RniI'
+alias record='rm ~/Downloads/appvideo.mov || xcrun simctl io booted recordVideo ~/Downloads/appvideo.mov'
+alias opendl='xcrun simctl openurl booted'
+
+function jca () {
+    re='^[0-9]+$'
+    if ! [[ $1 =~ $re ]] ; then
+        echo "error: Enter JIRA Ticket" >&2;
+        return 1;
+    elif [ -z $2 ] ; then
+        echo "error: Enter a comment";
+        return 1;
+    else
+        gca -m "[TRIP-$1] ${*:2}"
+    fi
+}
+
